### ISSUE TITLE
How to bind users

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/PMT#26]
Should I create a creator and assignee field on the issue. Or create a table 'issue_users' containing the issue number, the user id and the kind of link this user has with the ticket. This could simplify issue watchers, ...

**Comment by Mordeak** [comment]
Use issue_users. This way you can assign multiple users with the same task. Ex. project exists of different modules, users are responsible for maintaining different modules. Issue has to be solved in multiple modules with each module having another user responsible for maintaining it.

**Comment by NoUseFreak** [comment]
I'm still not sure about this. Binding them will simplify ORM handling immensely. 

Any thoughts? 

/cc @Ozmodiar @denhul @RustiSub

**Comment by Mordeak** [comment]
A seperate table would simplify issue history. Creator could be on the issue but assignee can change multiple items. Could put the fields assigned_on, accepted_on, finished_on in the table to get a more detailed issue history if we wanted.
