### ISSUE TITLE
Merge PMTUserBundle

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/PMT#29]
Merge the PMTUserBundle in PMTCoreBundle and PMTWebBundle. This should take in account the separation between presentation and core logic.

**Comment by ozmodiar** [comment]
Be aware that I register FOSUserBundle as the parent of the UserBundle in order to override the templates. How do we handle that if we merge this into Web and Core?

**Comment by NoUseFreak** [comment]
If only the templates where overwritten, we should be able to fully remote the UserBundle. The templates of every bundle can be overwritten in the `app`-folder.

Info: http://symfony.com/doc/2.0/book/templating.html#overriding-bundle-templates

**Comment by NoUseFreak** [comment]
Merged. 5cee0a984fe145251566a0d324b25ef550149327
