### ISSUE TITLE
Create standard issue lists

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/PMT#8]
Issues should be shown in 2 kinds of lists. (advanced and simple)

**advanced**
- type (icon?)
- code (project code + ticket id)
- summary
- assignee
- reporter
- priority
- status
- resolution
- created
- updated
- due date

**simple**
- type (icon?)
- key
- summary
- priority

**Comment by NoUseFreak** [comment]
Optional popovers for faster interaction.

http://twitter.github.io/bootstrap/javascript.html#popovers

**Comment by NoUseFreak** [comment]
Template provided in aa5d2acc79a39625f1c05d510430f284cdb2126b

**Comment by denhul** [comment]
Should I put the url to the images for status, priority, .. in the db?

@NoUseFreak, @Ozmodiar

**Comment by NoUseFreak** [comment]
Hardcode them for now. I created an issue to fix this later. #66

**Comment by NoUseFreak** [comment]
Maybe we should add a third view "basic" being between simple and advanded.

We can use the basic on all the places advanced is currently used, and use the advanced only in the issue navigator.

**Comment by denhul** [comment]
we could also use the simple view for this?

I agree on the usage of the advanced view in the issue navigator

**Comment by NoUseFreak** [comment]
Done in fa4e19feeb229dd1fe45adf17410ce76cf1e4c7d

**Comment by NoUseFreak** [comment]
Done in fa4e19feeb229dd1fe45adf17410ce76cf1e4c7d
